name: Record bundle stats
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!dependabot/**'
  pull_request_target:
    types: [opened, synchronize]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: yarn install
        run: yarn install

      - name: Build production version
        run: yarn build:stats
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}

      - name: Record bundle stats
        uses: birchill/good-bundle@main
        with:
          project: hikibiki
          bucket: bundlesize-stack-bundlestatsbucket-15h4d77z8q1hr
          destDir: hikibiki
          region: us-west-2
          awsAccessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
